fail_fast: true

repos:
# Python formatting and linting tools
- repo: https://github.com/psf/black
  rev: 25.9.0
  hooks:
    - id: black
      language_version: python3
      exclude: contrib/utilities/prm_tools.py
- repo: https://github.com/pycqa/isort
  rev: 6.0.1
  hooks:
    - id: isort
      args: ["--profile", "black"]
      exclude: contrib/utilities/prm_tools.py
# - repo: https://github.com/pycqa/flake8
#   rev: 7.3.0
#   hooks:
#     - id: flake8
#       args: [--max-line-length=80]
#       exclude: contrib/utilities/prm_tools.py